# Generated by Django 6.0.1 on 2026-03-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_add_privacy_to_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('guest', 'Guest')], default='user', help_text='Application-level role: admin > user > guest', max_length=10),
        ),
    ]
